### ISSUE TITLE
How can I control the UAVs?

### ISSUE THREAD

**Issue by LordonCN** [dji-m100-ros/dji_m100_controllers_gazebo#2]
Hi
Thank u for your afforts,I want to know can i use keyboard to control the uavs in gazebo?

**Comment by tahsinkose** [comment]
Yes you can, there are plenty of other packages around the web which supports this. Basically you will assign absolute twist commands to the keys you want and execute those commands with a dedicated node. Nevertheless, this is not an _issue_ for this repository per se. Therefore I'm closing it.
